<?php

use Magento\Checkout\Block\Cart\Grid;
use Magento\Framework\Escaper;

/**  @var $block Grid */
/** @var Escaper $escaper */

$mergedCells = ($this->helper(Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1);
$isShareCartEnabled = $this->helper(DeveloperHub\ShareCart\Helper\Config::class)->isShareCartEnabled() ?>
<?= $block->getChildHtml('form_before') ?>
<div>
    <form action="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
              {"validationURL" : "<?= $escaper->escapeUrl($block->getUrl('checkout/cart/updateItemQty')) ?>",
              "updateCartActionContainer": "#update_cart_action_container"}
          }'
          class="form form-cart">
        <?= $block->getBlockHtml('formkey') ?>
        <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
            <?php if ($block->getPagerHtml()): ?>
                <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                     data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?>
                </div>
            <?php endif ?>
            <table id="shopping-cart-table"
                   class="cart items data table"
                   data-mage-init='{"shoppingCart":{"emptyCartButton": ".action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
                <caption class="table-caption"><?= $escaper->escapeHtml(__('Shopping Cart Items')) ?></caption>
                <thead>
                <tr>
                    <th class="col item" scope="col"><span><?= $escaper->escapeHtml(__('Item')) ?></span></th>
                    <th class="col price" scope="col"><span><?= $escaper->escapeHtml(__('Price')) ?></span></th>
                    <th class="col qty" scope="col"><span><?= $escaper->escapeHtml(__('Qty')) ?></span></th>
                    <th class="col subtotal" scope="col"><span><?= $escaper->escapeHtml(__('Subtotal')) ?></span></th>
                </tr>
                </thead>
                <?php foreach ($block->getItems() as $item): ?>
                    <?= $block->getItemHtml($item) ?>
                <?php endforeach ?>
            </table>
            <?php if ($block->getPagerHtml()): ?>
                <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
                     data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?>
                </div>
            <?php endif ?>
        </div>
        <div class="cart main actions">
            <?php if ($block->getContinueShoppingUrl()): ?>
                <a class="action continue"
                   href="<?= $escaper->escapeUrl($block->getContinueShoppingUrl()) ?>"
                   title="<?= $escaper->escapeHtml(__('Continue Shopping')) ?>">
                    <span><?= $escaper->escapeHtml(__('Continue Shopping')) ?></span>
                </a>
            <?php endif; ?>
            <?php if ($block->getViewModel()->isClearShoppingCartEnabled()): ?>
                <button type="button"
                        name="update_cart_action"
                        data-cart-empty=""
                        value="empty_cart"
                        title="<?= $escaper->escapeHtml(__('Clear Shopping Cart')) ?>"
                        class="action clear" id="empty_cart_button">
                    <span><?= $escaper->escapeHtml(__('Clear Shopping Cart')) ?></span>
                </button>
            <?php endif ?>
            <?php if ($isShareCartEnabled): ?>
                <button type="button" class="popupBtn" data-modal-id="share-cart-modal">
                    <span>Share Shopping Cart </span>
                </button>
            <?php endif; ?>
            <button type="submit"
                    name="update_cart_action"
                    data-cart-item-update=""
                    value="update_qty"
                    title="<?= $escaper->escapeHtml(__('Update Shopping Cart')) ?>"
                    class="action update">
                <span><?= $escaper->escapeHtml(__('Update Shopping Cart')) ?></span>
            </button>
            <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
        </div>
    </form>
</div>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>
<div class="modal-outer-wrapper" id="share-cart-modal">
    <div class="modal-inner-wrapper">
        <div class="set-title">
            <strong>Share Cart</strong>
        </div>
        <form class="modal-form" id="cw-quote-form" method="post"
              action="<?= $block->getUrl('sharecart/index/sendemail') ?>">
            <input name="form_key" type="hidden" value="">
            <div class="form-group">
                <label>
                    <strong>Sender Name</strong>
                    <span>*</span>
                </label>
                <input type="text" class="form-control roundedInput " name="sender_name"
                       placeholder="Sender Name" required="">
            </div>
            <br>
            <div class="form-group">
                <label>
                    <strong>Sender e-mail address</strong>
                    <span>*</span>
                </label>
                <input type="email" class="form-control roundedInput" name="sender_email"
                       placeholder="Sender e-mail address" required="">
            </div>
            <br>
            <div class="form-group">
                <label>
                    <strong>Recipient name</strong>
                    <span>*</span>
                </label>
                <input type="text" class="form-control roundedInput" name="receiver_name"
                       placeholder="Recipient name" required="">
            </div>
            <br>
            <div class="form-group">
                <label>
                    <strong>Recipient e-mail address</strong>
                    <span>*</span>
                </label>
                <input type="email" class="form-control roundedInput" name="receiver_email"
                       placeholder="Recipient e-mail address" required="">
            </div>
            <br>
            <div class="form-group">
                <label>
                    <strong>Message</strong>
                </label>
                <textarea type="text" class="form-control roundedInput" name="message"
                          placeholder="Message"></textarea>
            </div>
            <br>
            <button name="submit" class="btn btn-primary rounded"> Send shopping cart </button>
        </form>
    </div>
</div>
<?php if ($isShareCartEnabled): ?>
<script type="text/x-magento-init">
    {
        "*": {
            "titleJs": {}
        }
    }
</script>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal',
            'mage/url',
        ],
        function ($, modal, urlBuilder) {
            $(document).ready(function () {
                let options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    modalClass: 'modal-form',
                    buttons: []
                };
                $('body').on('click', '#cw-quote-form .action.submit', function (e) {
                    e.preventDefault();
                    if ($('#cw-quote-form').valid()) {
                        $.ajax({
                            url: "<?= $block->getUrl('sharecart/index/sendemail') ?>",
                            type: 'POST',
                            dataType: 'JSON',
                            data: $('#cw-quote-form').serialize(),
                            showLoader: 'true',
                            success: function (response) {
                                if (response.success) {
                                    $('#share-cart-modal').hide();
                                    $('#cw-quote-response-message').show();
                                }
                            }
                        });
                    }
                });
            });
        }
    );
</script>
<?php endif; ?>
